use enum_iterator::Sequence;

#[derive(Debug, PartialEq, Sequence, Clone, Default)]
pub enum SaveDataVar {
    #[default]
    FileExists,
    //m_bNameList, whatever this is
    SaveDate,
    PlayTimeHours,
    PlayTimeMinutes,
    PlayTimeSeconds,
    StageFlagList,
    ScoreList,
    TimeTrialList,
    TimeTrialCoopList,
    FriendsFlagList,
    FriendsTalkList,
    StageMazeFlagList,
    LastStageId,
    LastGameModeId,
    Lives,
    MazeFlagList,
    MazesScoreList,
    FruitsGetNum,
    CapsuleGetNum,
    MedalGetNum,
    BombDotKillNum,
    DotKillNum,
    RevRollKillNum,
    ButtBounceKillNum,
    GhostKillNum,
    MagicKeyUnlocked,
    TrueEnding,
    MarathonUnlocked,
    MarathonHighScore,
    MarathonClear,
    LastGISaveArea,
    LoadInitScene,
    DLCApplyFlag,
    JukeBoxBGM,
    JukeBoxMode,
    JukeBoxLoop,
    JukeBoxOrder,
    JukeBoxFlag,
    JukeBoxUnlockFlagList,
    MedalNum,
    CapsuleFlag,
    StageCherryFlag,
    StageStrawberryFlag,
    StageOrangeFlag,
    StageAppleFlag,
    StageMelonFlag,
    StageCherryNum,
    StageStrawberryNum,
    StageOrangeNum,
    StageAppleNum,
    StageMelonNum,
    VillageCherryFlag,
    VillageStrawberryFlag,
    VillageOrangeFlag,
    VillageAppleFlag,
    VillageMelonFlag,
    VillageCherryGetNum,
    VillageStrawberryGetNum,
    VillageOrangeGetNum,
    VillageAppleGetNum,
    VillageMelonGetNum,
    // bitfield showing the overall game progress with village curscenes
    // with 0 it will play the into of the game
    VillageGFFlag,
    // camera settings
    CameraMode,
    CameraSpeedY,
    CameraSpeedX,
    CameraControlY,
    CameraControlX,
    CameraAssistFlag,
    CameraYAutoRotateFlag,
    SwimControlY,

    MissionFlag,
    //MissionProgress, // TODO can't figure out what this is, it's always full of 0
    MissionRewardFlag,
    PlayerSkinId,
    // array in the decomp but makes sense to treat these and 2 separate i32s
    PlayerSkinId2,
    FigureInfo,
    FigureDisplayInfo,
    GashaFlag,
    GashaLotteryNum,
    FlipKillNum,
    SupperHipStunNum,
    SuperDolphinKillNum,
    UnlockStageSelectFlag,
    GameLevel,
    EnterPast,
    OriginalFlag,
    OriginalStageNum,
    OriginalHighScore,
    PacManiaStageNum,
    PacmaniaHighScore,
    PacAttackLevelNum,
    PacAttackHighScore,
    HelpFlag,
    DroneSkinFlag,
    DroneSkinID,
    DroneReticleSpeed,
    DroneReticleColor,
    DroneVacuumRangeFlag,
    EarlyBonusFigureFlag,

    KeyConfigP1, // why is this not global :(
    KeyConfigP2,
    // sonic update exclusive
    GashaDLCFlag,
    FigureInfoDLC,
    EnterSonic,
    VillageSonicFlag,
    LoadInitSceneCollab,
    LoadInitSceneKind,
    LastStageIdCollab,
    LastStageIdKindCollab,
    PlayerSkinIdCollab,
    FigureDisplayInfoCollab,
    JukeBoxBGMCollab,
    JukeBoxModeCollab,
}

#[derive(Debug, Clone, Copy)]
pub enum SaveDataIntType {
    Bool,
    U32,
    I32,
    Arrayi32(u32), // stores its length
    //Arrayu32(u32),
    Arrayu8(u32),
    ArrayText(u32),
    SFigureDisplayInfoArray(u32),
}

#[derive(Debug, Clone)]
pub struct SaveFileData {
    pub var: SaveDataVar,
    pub variable_name: String,
    pub variable_name_simple: String,
    pub slot_base_add: u32,
    pub offset: u32,
    pub int_type: SaveDataIntType,
}

pub fn get_save_slot_base_add(slot: u8) -> u32 {
    match slot {
        1 => 0x298,
        2 => 0x7BC8,
        3 => 0xF4F8,
        4 => 0x16E28,
        _ => {
            println!(
                "Invalid slot sent! Using slot 1. Slot in function: {}",
                slot
            );
            0x298
        }
    }
}

pub fn bgm_music_str_to_name(music: i32) -> String {
    let music_name = match music {
        -1 => "(Disabled, using DLC music)",
        0 => "Opening",
        1 => "Prologue",
        2 => "Pac-Village",
        3 => "The Bear Basics",
        4 => "Canyon Chaos",
        5 => "Pac-Dot Pong",
        6 => "Clyde's Frog",
        7 => "B-Doing Woods",
        8 => "Treewood Forest",
        9 => "Butane Pain",
        10 => "Inky's Whimsy",
        11 => "Pac-Ranger's Theme",
        12 => "Ice River Run",
        13 => "Avalanche Alley",
        14 => "Blade Mountain",
        15 => "Pinky's Revenge",
        16 => "Into the Volcano!",
        17 => "Volcanic Panic",
        18 => "Magma Opus",
        19 => "Blinky in the Caldera",
        20 => "Scuba Duba",
        21 => "Shark Attack",
        22 => "Yellow Pac-Marine",
        23 => "Whale on a Sub",
        24 => "Haunted Broadwalk",
        25 => "Night Crawling",
        26 => "Ghost Bayou",
        27 => "Climax",
        28 => "Spooky (Phase 1)",
        29 => "Spooky (Phase 2)",
        30 => "Ending",
        31 => "Credits",
        32 => "Results",
        33 => "Golden Fruit",
        34 => "Power Pellets",
        35 => "Pac-Village (Arcade Remix)",
        36 => "Clyde's Frog (Speedy Mix)",
        37 => "Inky's Whimsy (Speedy Mix)",
        38 => "Pinky's Revenge (Speedy Mix)",
        40 => "Whale on a Sub (Speedy Mix)",
        42 => "Game Over",
        46 => "Deadly Poisonous Meadows",
        47 => "A Long Poisonous Tongue",
        48 => "Harsh Harsh Winds",
        49 => "Hunter of Darkness",
        50 => "Pro Thunder Skater",
        51 => "Boom! Boom! Clap!",
        52 => "Hot! Fire Trouble",
        53 => "Blinky in the Caldera",
        54 => "Sharks Everywhere",
        55 => "Pac-Marine Battle!",
        56 => "Clumsy Bayou",
        57 => "Legendary Story (Phase 1)",
        58 => "Legendary Story (Phase 2)",
        59 => "A Long Poisonous Tongue (Speedy Mix)",
        60 => "Hunter of Darkness (Speedy Mix)",
        61 => "Boom! Boom! Clap! (Speedy Mix)",
        62 => "Pac-Marine Battle! (Speedy Mix)",
        65 => "Flying Dark Shadow",
        66 => "Pac-Village (Pac-Knight)",
        70 => "Ending (Pac-Knight)",
        71 => "PAC-MANIAC45",
        72 => "Start Music",
        73 => "Coffee Break Music",
        75 => "Block Town Music (Japan Version)",
        76 => "Pacman's Park (Japan Version)",
        77 => "Sandbox Land",
        78 => "Jungly Steps",
        79 => "Menu Selection",
        80 => "Puzzle Fever",
        81 => "The Can-Can",
        82 => "Blinky in the Caldera (Phase 1)",
        83 => "Blinky in the Caldera (Phase 2)",
        84 => "Burning Hot Beats (Phase 1)",
        85 => "Burning Hot Beats (Phase 2)",
        _ => "(Invalid)",
    }
    .to_string();

    format!("{} {}", music, music_name)
}

pub fn bgm_music_str_to_name_collab(music: i32) -> String {
        let music_name = match music {
        -1 => "(Disabled, using non DLC music)",
        // to use in m_iJukeBoxBGMKindCollabo
        86 => "Supersonic Tricky Railroad",
        87 => "South Pac-Island",
        88 => "GREEN HILL: ACT1",
        89 => "GREEN HILL: ACT2 - Normal",
        93 => "BOSS BATTLE: DEATH EGG ROBOT",
        94 => "Results",
        95 => "Results (S-Rank)",
        96 => "Act Clear",
        _ => "(Invalid)",
    }
    .to_string();

    format!("{} {}", music, music_name)
}

pub fn costume_int_to_name(costume_id: i32) -> String {
    let costume_name = match costume_id {
        -1 => "(Disabled)",
        0x00 => "No Costume",
        0x01 => "Green Hunter",
        0x02 => "Brown Hunter",
        0x03 => "Blue Hunter",
        0x04 => "Blue Street",
        0x05 => "Red Street",
        0x06 => "Pink Street",
        0x07 => "Brown Cowboy",
        0x08 => "Red Cowboy",
        0x09 => "Pink Cowboy",
        0x0a => "Brown Ushanka",
        0x0b => "Red Ushanka",
        0x0c => "Blue Ushanka",
        0x0d => "White Explorer",
        0x0e => "Green Explorer",
        0x0f => "Pink Explorer",
        0x10 => "Blue Diver",
        0x11 => "Green Diver",
        0x12 => "Pink Diver",
        0x13 => "Blinky",
        0x14 => "Inky",
        0x15 => "Clyde",
        0x16 => "Pinky",
        0x17 => "Black Magician",
        0x18 => "Purple Magician",
        0x19 => "Green Magician",
        0x1a => "Pac-Knight",
        0x1b => "Toc-Man",
        0x1c => "Pac-Wizard",
        0x1d => "Orson",
        0x1e => "Pac-Land",
        0x1f => "Spooky",
        0x20 => "Sonic",
        _ => "(Invalid)",
    }
    .to_string();

    format!("{} {}", costume_id, costume_name)
}

pub fn int_to_stage_name(id: usize, pac_village_start: bool) -> String {
    let id_to_match = if pac_village_start { id } else { id + 1 };

    match id_to_match {
        0 => "Pac-Village",
        1 => "The Bear Basics",
        2 => "Canyon Chaos",
        3 => "Pac-Dot Pond",
        4 => "Clyde's Frog",
        5 => "B-Doing Woods",
        6 => "Treewood Forest",
        7 => "Butane Pain",
        8 => "Inky's Whimsy",
        9 => "Ice River Run",
        10 => "Avalanche Alley",
        11 => "Blade Mountain",
        12 => "Pinky's Revenge",
        13 => "Into The Volcano!",
        14 => "Volcanic Panic",
        15 => "Magma Opus",
        16 => "Blinky in the Caldera",
        17 => "Scuba Duba",
        18 => "Shark Attack",
        19 => "Yellow Pac-Marine",
        20 => "Whale on a Sub",
        21 => "Haunted Boardwalk",
        22 => "Night Crawling",
        23 => "Ghost Bayou",
        24 => "Spooky",
        25 => "Deadly Poisonous Meadows",
        26 => "A Long Poisonous Tongue",
        27 => "Harsh Harsh Winds",
        28 => "Hunter Of Darkness",
        29 => "Pro Thunder Skater",
        30 => "Boom! Boom! Clap!",
        31 => "Hot! Fire Trouble",
        32 => "Burning Hot Beats",
        33 => "Sharks Everywhere",
        34 => "Pac-Marine Battle!",
        35 => "Clumsy Bayou",
        36 => "Legendary Story",
        37 => "Flying Dark Shadow",
        38 => "Rolling Around On the Island",
        39 => "Supersonic Tricky Railroad",
        40 => "300 IQ Evil Genius",
        _ => "Unknown",
    }
    .to_string()
}
pub fn int_to_mission_level(id: usize) -> String {
    match id {
        0 => "Pac-Village",
        1 | 2 | 3 => "The Bear Basics",
        4 | 5 | 6 => "Canyon Chaos",
        7 | 8 | 9 => "Pac-Dot Pond",
        10 | 11 => "Clyde's Frog",
        12 | 13 | 14 => "B-Doing Woods",
        15 | 16 | 17 => "Treewood Forest",
        18 | 19 | 20 => "Butane Pain",
        21 | 22 => "Inky's Whimsy",
        23 | 24 | 25 => "Ice River Run",
        26 | 27 | 28 => "Avalanche Alley",
        29 | 30 | 31 => "Blade Mountain",
        32 | 33 => "Pinky's Revenge",
        34 | 35 | 36 => "Into The Volcano!",
        37 | 38 | 39 => "Volcanic Panic",
        40 | 41 | 42 => "Magma Opus",
        43 | 44 => "Blinky in the Caldera",
        45 | 46 | 47 => "Scuba Duba",
        48 | 49 | 50 => "Shark Attack",
        51 | 52 | 53 => "Yellow Pac-Marine",
        54 | 55 => "Whale on a Sub",
        56 | 57 | 58 => "Haunted Boardwalk",
        59 | 60 | 61 => "Night Crawling",
        62 | 63 | 64 => "Ghost Bayou",
        65 | 66 => "Spooky",
        67 | 68 | 69 => "Deadly Poisonous Meadows",
        70 | 71 => "A Long Poisonous Tongue",
        72 | 73 | 74 => "Harsh Harsh Winds",
        75 | 76 => "Hunter Of Darkness",
        77 | 78 | 79 => "Pro Thunder Skater",
        80 | 81 => "Boom! Boom! Clap!",
        82 | 83 | 84 => "Hot! Fire Trouble",
        85 | 86 => "Burning Hot Beats",
        87 | 88 | 89 => "Sharks Everywhere",
        90 | 91 => "Pac-Marine Battle!",
        92 | 93 | 94 => "Clumsy Bayou",
        95 | 96 => "Legendary Story",
        97 | 98 => "Flying Dark Shadow",
        99 | 100 | 101 => "Rolling Around On the Island",
        102 | 103 | 104 => "Supersonic Tricky Railroad",
        105 | 106 => "300 IQ Evil Genius",
        _ => "Unknown",
    }
    .to_string()
}

pub fn int_to_maze_name(id: usize) -> String {
    match id {
        0 => "1-1",
        1 => "1-2",
        2 => "2-1",
        3 => "2-2",
        4 => "2-3",
        5 => "3-1",
        6 => "3-2",
        7 => "3-3",
        8 => "4-1",
        9 => "4-2",
        10 => "4-3",
        11 => "5-1",
        12 => "5-2",
        13 => "6-1",
        14 => "6-2",
        _ => "Unknown",
    }
    .to_string()
}

pub fn array_index_to_input_type(i: usize) -> String {
    match i {
        48 => "KB Jump",
        49 => "KB Pac-Dot Attack",
        50 => "KB Flip Kick",
        51 => "KB Rev Roll",
        53 => "KB Flutter",
        57 => "KB Reset Camera",
        72 => "Controller Jump",
        73 => "Controller Pac-Dot Attack",
        74 => "Controller Flip Kick",
        75 => "Controller Rev Roll",
        77 => "Controller Flutter",
        81 => "Controller Reset Camera",
        98 => "KB Change Maze Zoom",
        122 => "Controller Change Maze Zoom",
        432 => "KB Climb cliff",
        434 => "KB Let go of cliff",
        456 => "Controller Climb Cliff",
        458 => "Controller Let go of Cliff",
        480 => "KB Dolphin Kick",
        485 => "KB Float",
        495 => "KB Dive",
        503 => "Controller Dolphin Kick",
        509 => "Controller Float",
        519 => "Controller Dive",
        _ => return i.to_string(),
    }
    .to_string()
}

pub fn int_to_key(key: i64) -> String {
    let key_str = match key {
        1 => "Space",
        15 => "A",
        16 => "B",
        17 => "C",
        18 => "D",
        19 => "E",
        20 => "F",
        21 => "G",
        22 => "H",
        23 => "I",
        24 => "J",
        25 => "K",
        26 => "L",
        27 => "M",
        28 => "N",
        29 => "O",
        30 => "P",
        31 => "Q",
        32 => "R",
        33 => "S",
        34 => "T",
        35 => "U",
        36 => "V",
        37 => "W",
        38 => "X",
        39 => "Y",
        40 => "Z",
        51 => "Left Shift",
        55 => "Left Ctrl",
        1000 => "Left Click",
        1001 => "Right Click",
        _ => return key.to_string(),
    };

    format!("{key} {key_str}")
}

pub fn int_to_controller_btn(btn: i64) -> String {
    let btn_str = match btn {
        0 => "A",
        1 => "B",
        2 => "X",
        3 => "Y",
        4 => "L",
        5 => "R",
        14 => "ZL / L2 / LT",
        15 => "ZR / R2 / RT",
        8 => "Left Stick Click",
        9 => "Right Stick Click",
        _ => return btn.to_string(),
    };

    format!("{btn} {btn_str}")
}
