use enum_iterator::Sequence;

#[derive(Debug, PartialEq, Sequence)]
pub enum SaveDataVar {
    FileExists,
    SaveDate,
    PlayTimeHours,
    PlayTimeMinutes,
    PlayTimeSeconds,
    StageFlagList,
    ScoreList,
    TimeTrialList,
    TimeTrialCoopList,
    FriendsFlagList,
    FriendsTalkList,
    StageMazeFlagList,
    LastStageId,
    LastGameModeId,
    Lives,
    MazeFlagList,
    MazesScoreList,
    FruitsGetNum,
    CapsuleGetNum,
    MedalGetNum,
    BombDotKillNum,
    DotKillNum,
    RevRollKillNum,
    ButtBounceKillNum,
    GhostKillNum,
    MagicKeyUnlocked,
    TrueEnding,
    MarathonUnlocked,
    MarathonHighScore,
    MarathonClear,
    LastGISaveArea,
    LoadInitScene,
    DLCApplyFlag,
    JukeBoxBGM,
    JukeBoxMode,
    JukeBoxLoop,
    JukeBoxOrder,
    JukeBoxFlag,
    JukeBoxUnlockFlagList,
    MedalNum,
    //CapsuleFlag // TODO exp with this later, too many of these
    StageCherryFlag,
    StageStrawberryFlag,
    StageOrangeFlag,
    StageAppleFlag,
    StageMelonFlag,
    StageCherryNum,
    StageStrawberryNum,
    StageOrangeNum,
    StageAppleNum,
    StageMelonNum,
    VillageCherryFlag,
    VillageStrawberryFlag,
    VillageOrangeFlag,
    VillageAppleFlag,
    VillageMelonFlag,
    VillageCherryGetNum,
    VillageStrawberryGetNum,
    VillageOrangeGetNum,
    VillageAppleGetNum,
    VillageMelonGetNum,
    
    JukeBoxBGMCollab,
    JukeBoxModeCollab,
}

#[derive(Debug)]
pub enum SaveDataIntType {
    Bool,
    U32,
    I32,
    Arrayi32(u32), // stores its length
    Arrayu32(u32),
    Arrayu8(u32),
    ArrayText(u32),
}

#[derive(Debug)]
pub struct SaveFileData {
    pub var: SaveDataVar,
    pub variable_name: String,
    pub variable_name_simple: String,
    pub slot_base_add: u32,
    pub offset: u32,
    pub int_type: SaveDataIntType,
}

pub fn get_save_slot_base_add(slot: u8) -> u32 {
    match slot {
        1 => 0x298,
        2 => 0x7BC8,
        3 => 0xF4F8,
        4 => 0x16E28,
        _ => {
            println!(
                "Invalid slot sent! Using slot 1. Slot in function: {}",
                slot
            );
            0x298
        }
    }
}

pub fn bgm_music_str_to_name(music: &str) -> String {
    match music {
        "-1" => "Disabled (See DLC/No DLC Music)",
        "0" => "Opening",
        "1" => "Prologue",
        "2" => "Pac-Village",
        "3" => "The Bear Basics",
        "4" => "Canyon Chaos",
        "5" => "Pac-Dot Pong",
        "6" => "Clyde's Frog",
        "7" => "B-Doing Woods",
        "8" => "Treewood Forest",
        "9" => "Butane Pain",
        "10" => "Inky's Whimsy",
        "11" => "Pac-Ranger's Theme",
        "12" => "Ice River Run",
        "13" => "Avalanche Alley",
        "14" => "Blade Mountain",
        "15" => "Pinky's Revenge",
        "16" => "Into the Volcano!",
        "17" => "Volcanic Panic",
        "18" => "Magma Opus",
        "19" => "Blinky in the Caldera",
        "20" => "Scuba Duba",
        "21" => "Shark Attack",
        "22" => "Yellow Pac-Marine",
        "23" => "Whale on a Sub",
        "24" => "Haunted Broadwalk",
        "25" => "Night Crawling",
        "26" => "Ghost Bayou",
        "27" => "Climax",
        "28" => "Spooky (Phase 1)",
        "29" => "Spooky (Phase 2)",
        "30" => "Ending",
        "31" => "Credits",
        "32" => "Results",
        "33" => "Golden Fruit",
        "34" => "Power Pellets",
        "35" => "Pac-Village (Arcade Remix)",
        "36" => "Clyde's Frog (Speedy Mix)",
        "37" => "Inky's Whimsy (Speedy Mix)",
        "38" => "Pinky's Revenge (Speedy Mix)",
        "40" => "Whale on a Sub (Speedy Mix)",
        "42" => "Game Over",
        "46" => "Deadly Poisonous Meadows",
        "47" => "A Long Poisonous Tongue",
        "48" => "Harsh Harsh Winds",
        "49" => "Hunter of Darkness",
        "50" => "Pro Thunder Skater",
        "51" => "Boom! Boom! Clap!",
        "52" => "Hot! Fire Trouble",
        "53" => "Blinky in the Caldera",
        "54" => "Sharks Everywhere",
        "55" => "Pac-Marine Battle!",
        "56" => "Clumsy Bayou",
        "57" => "Legendary Story (Phase 1)",
        "58" => "Legendary Story (Phase 2)",
        "59" => "A Long Poisonous Tongue (Speedy Mix)",
        "60" => "Hunter of Darkness (Speedy Mix)",
        "61" => "Boom! Boom! Clap! (Speedy Mix)",
        "62" => "Pac-Marine Battle! (Speedy Mix)",
        "65" => "Flying Dark Shadow",
        "66" => "Pac-Village (Pac-Knight)",
        "70" => "Ending (Pac-Knight)",
        "71" => "PAC-MANIAC45",
        "72" => "Start Music",
        "73" => "Coffee Break Music",
        // TODO i haven't unlocked 7 songs lol
        "82" => "Blinky in the Caldera (Phase 1)",
        "83" => "Blinky in the Caldera (Phase 2)",
        "84" => "Burning Hot Beats (Phase 1)",
        "85" => "Burning Hot Beats (Phase 2)",
        "86" => "Supersonic Tricky Railroad",
        "87" => "South Pac-Island",
        "88" => "GREEN HILL: ACT1",
        "89" => "GREEN HILL: ACT2 - Normal",
        "93" => "BOSS BATTLE: DEATH EGG ROBOT",
        "94" => "Results",
        "95" => "Results (S-Rank)",
        "96" => "Act Clear",
        _ => music,
    }
    .to_string()
}