use enum_iterator::Sequence;

#[derive(Debug, PartialEq, Sequence, Clone)]
pub enum SaveDataVar {
    FileExists,
    //m_bNameList, whatever this is
    SaveDate,
    PlayTimeHours,
    PlayTimeMinutes,
    PlayTimeSeconds,
    StageFlagList,
    ScoreList,
    TimeTrialList,
    TimeTrialCoopList,
    FriendsFlagList,
    FriendsTalkList,
    StageMazeFlagList,
    LastStageId,
    LastGameModeId,
    Lives,
    MazeFlagList,
    MazesScoreList,
    FruitsGetNum,
    CapsuleGetNum,
    MedalGetNum,
    BombDotKillNum,
    DotKillNum,
    RevRollKillNum,
    ButtBounceKillNum,
    GhostKillNum,
    MagicKeyUnlocked,
    TrueEnding,
    MarathonUnlocked,
    MarathonHighScore,
    MarathonClear,
    LastGISaveArea,
    LoadInitScene,
    DLCApplyFlag,
    JukeBoxBGM,
    JukeBoxMode,
    JukeBoxLoop,
    JukeBoxOrder,
    JukeBoxFlag,
    JukeBoxUnlockFlagList,
    MedalNum,
    //CapsuleFlag // TODO exp with this later, too many of these
    StageCherryFlag,
    StageStrawberryFlag,
    StageOrangeFlag,
    StageAppleFlag,
    StageMelonFlag,
    StageCherryNum,
    StageStrawberryNum,
    StageOrangeNum,
    StageAppleNum,
    StageMelonNum,
    VillageCherryFlag,
    VillageStrawberryFlag,
    VillageOrangeFlag,
    VillageAppleFlag,
    VillageMelonFlag,
    VillageCherryGetNum,
    VillageStrawberryGetNum,
    VillageOrangeGetNum,
    VillageAppleGetNum,
    VillageMelonGetNum,
    VillageGFFlag, // grand finale? idk what this is
    // camera settings
    CameraMode,
    CameraSpeedY,
    CameraSpeedX,
    CameraControlY,
    CameraControlX,
    CameraAssistFlag,
    CameraYAutoRotateFlag,
    SwimControlY,

    //MissionProgress, // TODO what is this?
    MissionRewardFlag,
    PlayerSkinId,
    // array in the decomp but makes sense to treat these and 2 separate i32s
    PlayerSkinId2,
    FigureInfo,
    FigureDisplayInfo,
    GashaFlag,
    GashaLotteryNum,
    FlipKillNum,
    SupperHipStunNum,
    SuperDolphinKillNum,
    UnlockStageSelectFlag,
    GameLevel,
    EnterPast,
    OriginalFlag,
    OriginalStageNum,
    OriginalHighScore,
    PacManiaStageNum,
    PacmaniaHighScore,
    PacAttackLevelNum,
    PacAttackHighScore,
    HelpFlag,
    //DroneSkinFlag // TODO
    //DroneSkinID // TODO
    DroneReticleSpeed,
    DroneReticleColor,
    DroneVacuumRangeFlag,
    EarlyBonusFigureFlag,

    KeyConfigP1, // why is this not global :(
    KeyConfigP2,
    // sonic update exclusive
    GashaDLCFlag,
    FigureInfoDLC,
    EnterSonic,
    VillageSonicFlag,
    LoadInitSceneCollab,
    LoadInitSceneKind,
    LastStageIdCollab,
    LastStageIdKindCollab,
    PlayerSkinIdCollab,
    FigureDisplayInfoCollab,
    JukeBoxBGMCollab,
    JukeBoxModeCollab,
}

#[derive(Debug, Clone)]
pub enum SaveDataIntType {
    Bool,
    U32,
    I32,
    Arrayi32(u32), // stores its length
    Arrayu32(u32),
    Arrayu8(u32),
    ArrayText(u32),
    SFigureDisplayInfoArray(u32),
}

#[derive(Debug, Clone)]
pub struct SaveFileData {
    pub var: SaveDataVar,
    pub variable_name: String,
    pub variable_name_simple: String,
    pub slot_base_add: u32,
    pub offset: u32,
    pub int_type: SaveDataIntType,
}

pub fn get_save_slot_base_add(slot: u8) -> u32 {
    match slot {
        1 => 0x298,
        2 => 0x7BC8,
        3 => 0xF4F8,
        4 => 0x16E28,
        _ => {
            println!(
                "Invalid slot sent! Using slot 1. Slot in function: {}",
                slot
            );
            0x298
        }
    }
}

pub fn bgm_music_str_to_name(music: i32) -> String {
    match music {
        -1 => "-1 Disabled (See DLC/No DLC Music)",
        0 => "00 Opening",
        1 => "01 Prologue",
        2 => "02 Pac-Village",
        3 => "03 The Bear Basics",
        4 => "04 Canyon Chaos",
        5 => "05 Pac-Dot Pong",
        6 => "06 Clyde's Frog",
        7 => "07 B-Doing Woods",
        8 => "08 Treewood Forest",
        9 => "09 Butane Pain",
        10 => "0A Inky's Whimsy",
        11 => "0B Pac-Ranger's Theme",
        12 => "0C Ice River Run",
        13 => "0D Avalanche Alley",
        14 => "0E Blade Mountain",
        15 => "0F Pinky's Revenge",
        16 => "10 Into the Volcano!",
        17 => "Volcanic Panic",
        18 => "Magma Opus",
        19 => "Blinky in the Caldera",
        20 => "Scuba Duba",
        21 => "Shark Attack",
        22 => "Yellow Pac-Marine",
        23 => "Whale on a Sub",
        24 => "Haunted Broadwalk",
        25 => "Night Crawling",
        26 => "Ghost Bayou",
        27 => "Climax",
        28 => "Spooky (Phase 1)",
        29 => "Spooky (Phase 2)",
        30 => "Ending",
        31 => "Credits",
        32 => "Results",
        33 => "Golden Fruit",
        34 => "Power Pellets",
        35 => "Pac-Village (Arcade Remix)",
        36 => "Clyde's Frog (Speedy Mix)",
        37 => "Inky's Whimsy (Speedy Mix)",
        38 => "Pinky's Revenge (Speedy Mix)",
        40 => "Whale on a Sub (Speedy Mix)",
        42 => "Game Over",
        46 => "Deadly Poisonous Meadows",
        47 => "A Long Poisonous Tongue",
        48 => "Harsh Harsh Winds",
        49 => "Hunter of Darkness",
        50 => "Pro Thunder Skater",
        51 => "Boom! Boom! Clap!",
        52 => "Hot! Fire Trouble",
        53 => "Blinky in the Caldera",
        54 => "Sharks Everywhere",
        55 => "Pac-Marine Battle!",
        56 => "Clumsy Bayou",
        57 => "Legendary Story (Phase 1)",
        58 => "Legendary Story (Phase 2)",
        59 => "A Long Poisonous Tongue (Speedy Mix)",
        60 => "Hunter of Darkness (Speedy Mix)",
        61 => "Boom! Boom! Clap! (Speedy Mix)",
        62 => "Pac-Marine Battle! (Speedy Mix)",
        65 => "Flying Dark Shadow",
        66 => "Pac-Village (Pac-Knight)",
        70 => "Ending (Pac-Knight)",
        71 => "PAC-MANIAC45",
        72 => "Start Music",
        73 => "Coffee Break Music",
        // TODO i haven't unlocked 7 songs lol
        82 => "Blinky in the Caldera (Phase 1)",
        83 => "Blinky in the Caldera (Phase 2)",
        84 => "Burning Hot Beats (Phase 1)",
        85 => "Burning Hot Beats (Phase 2)",
        86 => "Supersonic Tricky Railroad",
        87 => "South Pac-Island",
        88 => "GREEN HILL: ACT1",
        89 => "GREEN HILL: ACT2 - Normal",
        93 => "BOSS BATTLE: DEATH EGG ROBOT",
        94 => "Results",
        95 => "Results (S-Rank)",
        96 => "Act Clear",
        _ => return format!("Unknown: {}", music),
    }
    .to_string()
}

pub fn costume_int_to_name(costume_id: i32) -> String {
    match costume_id {
        0x00 => "00 No Costume",
        0x01 => "01 Green Hunter",
        0x02 => "02 Brown Hunter",
        0x03 => "03 Blue Hunter",
        0x04 => "04 Blue Street",
        0x05 => "05 Red Street",
        0x06 => "06 Pink Street",
        0x07 => "07 Brown Cowboy",
        0x08 => "08 Red Cowboy",
        0x09 => "09 Pink Cowboy",
        0x0a => "0A Brown Ushanka",
        0x0b => "0B Red Ushanka",
        0x0c => "0C Blue Ushanka",
        0x0d => "0D White Explorer",
        0x0e => "0E Green Explorer",
        0x0f => "0F Pink Explorer",
        0x10 => "10 Blue Diver",
        0x11 => "11 Green Diver",
        0x12 => "12 Pink Diver",
        0x13 => "13 Blinky",
        0x14 => "14 Inky",
        0x15 => "15 Clyde",
        0x16 => "16 Pinky",
        0x17 => "17 Black Magician",
        0x18 => "18 Purple Magician",
        0x19 => "19 Green Magician",
        0x1a => "1A Pac-Knight",
        0x1b => "1B Toc-Man",
        0x1c => "1C Pac-Wizard",
        0x1d => "1D Orson",
        0x1e => "1E Pac-Land",
        0x1f => "1F Spooky",
        0x20 => "20 Sonic",
        _ => return format!("Unknown: {}", costume_id),
    }
    .to_string()
}

pub fn int_to_stage_name(id: usize, pac_village_start: bool) -> String {
    let id_to_match = if pac_village_start { id } else { id + 1 };

    match id_to_match {
        0 => "Pac-Village",
        1 => "The Bear Basics",
        2 => "Canyon Chaos",
        3 => "Pac-Dot Pond",
        4 => "Clyde's Frog",
        5 => "B-Doing Woods",
        6 => "Treewood Forest",
        7 => "Butane Pain",
        8 => "Inky's Whimsy",
        9 => "Ice River Run",
        10 => "Avalanche Alley",
        11 => "Blade Mountain",
        12 => "Pinky's Revenge",
        13 => "Into The Volcano!",
        14 => "Volcanic Panic",
        15 => "Magma Opus",
        16 => "Blinky in the Caldera",
        17 => "Scuba Duba",
        18 => "Shark Attack",
        19 => "Yellow Pac-Marine",
        20 => "Whale on a Sub",
        21 => "Haunted Boardwalk",
        22 => "Night Crawling",
        23 => "Ghost Bayou",
        24 => "Spooky",
        25 => "Deadly Poisonous Meadows",
        26 => "A Long Poisonous Tongue",
        27 => "Harsh Harsh Winds",
        28 => "Hunter Of Darkness",
        29 => "Pro Thunder Skater",
        30 => "Boom! Boom! Clap!",
        31 => "Hot! Fire Trouble",
        32 => "Burning Hot Beats",
        33 => "Sharks Everywhere",
        34 => "Pac-Marine Battle!",
        35 => "Clumsy Bayou",
        36 => "Legendary Story",
        37 => "Flying Dark Shadow",
        38 => "Rolling Around On the Island",
        39 => "Supersonic Tricky Railroad",
        40 => "300 IQ Evil Genius",
        _ => "Unknown",
    }
    .to_string()
}

pub fn int_to_maze_name(id: usize) -> String {
    match id {
        0 => "1-1",
        1 => "1-2",
        2 => "2-1",
        3 => "2-2",
        4 => "2-3",
        5 => "3-1",
        6 => "3-2",
        7 => "3-3",
        8 => "4-1",
        9 => "4-2",
        10 => "4-3",
        11 => "5-1",
        12 => "5-2",
        13 => "6-1",
        14 => "6-2",
        _ => "Unknown",
    }
    .to_string()
}
